# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 07:18
from __future__ import unicode_literals

import clients.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='addons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_name', models.CharField(default='', max_length=1000)),
                ('monthly_price', models.CharField(default='', max_length=1000)),
                ('view_stat', models.CharField(choices=[('active', 'active'), ('hidden', 'hidden')], max_length=1000)),
                ('addon_description', models.TextField(default='')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='invoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.TextField(default='')),
                ('item_name', models.TextField(default='')),
                ('item_description', models.TextField(default='')),
                ('item_quantity', models.CharField(default='', max_length=100)),
                ('item_cost', models.CharField(default='', max_length=1000)),
                ('item_total_cost', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='project_addons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_status', models.CharField(choices=[('Deactivated', 'Deactivated'), ('Activated', 'Activated')], default='Deactivated', max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('addons_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.addons')),
            ],
        ),
        migrations.CreateModel(
            name='projectFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_title', models.CharField(default='', max_length=1000)),
                ('document_file', models.FileField(upload_to=clients.models.get_project_document)),
                ('view_stat', models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='show', max_length=500)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(default=b'AF0684CE', editable=False, max_length=200, unique=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('due_date', models.DateField(verbose_name=datetime.datetime(2018, 8, 14, 12, 48, 25, 786345))),
                ('notes', models.TextField(default='')),
                ('invoice_total_cost', models.CharField(default='0', max_length=1000)),
                ('invoice_status', models.CharField(choices=[('generating', 'generating'), ('pending', 'pending'), ('paid', 'paid'), ('failed', 'failed')], default='generating', max_length=1000)),
                ('invoice_type', models.CharField(choices=[('online', 'online'), ('cash', 'cash')], default='online', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='projectPosts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(default='')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='projectReports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_extension', models.CharField(default='', max_length=1000)),
                ('file_title', models.CharField(default='', max_length=1000)),
                ('document_file', models.FileField(upload_to=clients.models.get_project_document)),
                ('view_stat', models.CharField(choices=[('waiting', 'waiting'), ('approved', 'approved')], default='waiting', max_length=500)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(default='', max_length=1000)),
                ('website_url', models.CharField(default='', max_length=1000)),
                ('project_description', models.TextField(default='')),
                ('project_status', models.CharField(choices=[('Deactivated', 'Deactivated'), ('Activated', 'Activated'), ('Halted', 'Halted'), ('Completed', 'Completed')], default='Deactivated', max_length=1000)),
                ('subscription_plans_name', models.CharField(default='', max_length=1000)),
                ('subscription_plans_monthly_price', models.CharField(default='', max_length=1000)),
                ('subscription_plans_setup_fee', models.CharField(default='', max_length=1000)),
                ('subscription_plans_description', models.CharField(default='', max_length=1000)),
                ('subscription_plans_id', models.CharField(default='', max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='serviceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='', max_length=1000)),
                ('serivce_description', models.CharField(default='', max_length=1000)),
                ('service_price', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='subscription_plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='', max_length=1000)),
                ('monthly_price', models.CharField(default='', max_length=1000)),
                ('setup_fee', models.CharField(default='', max_length=1000)),
                ('view_stat', models.CharField(choices=[('active', 'active'), ('hidden', 'hidden')], max_length=1000)),
                ('plan_description', models.TextField(default='')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='taxSlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(default='', max_length=1000)),
                ('tax_percent', models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='projectreports',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.projects'),
        ),
        migrations.AddField(
            model_name='projectreports',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.projectReportType'),
        ),
        migrations.AddField(
            model_name='projectreports',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectposts',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.projects'),
        ),
        migrations.AddField(
            model_name='projectinvoice',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.projects'),
        ),
        migrations.AddField(
            model_name='projectinvoice',
            name='taxable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.taxSlab'),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.projects'),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project_addons',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.projects'),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.projectInvoice'),
        ),
    ]
