# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 08:54
from __future__ import unicode_literals

import clients.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvoice',
            name='due_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 8, 14, 14, 24, 13, 913279)),
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, default=clients.models.increment_invoice_number, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='taxslab',
            name='tax_percent',
            field=models.CharField(default='5', max_length=100),
        ),
    ]
